# Generated by Django 3.0.5 on 2020-05-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200513_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='active',
        ),
    ]
