# Generated by Django 3.0.5 on 2020-05-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_designer_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='user',
        ),
    ]
