# Generated by Django 3.0.5 on 2020-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200518_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='email',
            field=models.EmailField(default=True, max_length=150, null=True),
        ),
    ]
