# Generated by Django 3.0.5 on 2020-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200520_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(default=True, max_length=150, null=True),
        ),
    ]
