# Generated by Django 3.0.5 on 2020-05-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_personalinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(default=True, null=True, upload_to='product_images')),
                ('description', models.TextField()),
            ],
        ),
    ]
