# Generated by Django 3.0.5 on 2020-06-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_printers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('modelName', models.CharField(max_length=250)),
                ('imageOne', models.ImageField(default=True, null=True, upload_to='printer_images')),
                ('imageTwo', models.ImageField(default=True, null=True, upload_to='printer_images')),
                ('imageThree', models.ImageField(default=True, null=True, upload_to='printer_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Printers',
        ),
    ]
