# Generated by Django 3.0.5 on 2020-06-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200601_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerowner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Designer',
        ),
        migrations.DeleteModel(
            name='PrinterOwner',
        ),
    ]
