# Generated by Django 3.0.5 on 2020-06-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200603_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='DimensionalPrinter',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
