# Generated by Django 3.0.5 on 2020-04-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200402_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='billing_adddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='shipping_adddress',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
