# Generated by Django 3.0.5 on 2020-05-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_colours',
            field=models.ManyToManyField(null=True, to='cart.ColourVariation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(null=True, to='cart.SizeVariation'),
        ),
    ]
