# Generated by Django 3.0.5 on 2020-05-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200503_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
