# Generated by Django 3.0.5 on 2020-05-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_designvariation_threedimensionaldesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='designvariation',
            name='image',
            field=models.ImageField(null=True, upload_to='design_types'),
        ),
    ]
