# Generated by Django 3.0.5 on 2020-05-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_designvariation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedimensionaldesign',
            name='type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
