# Generated by Django 3.0.5 on 2020-05-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_threedimensionaldesign_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threedimensionaldesign',
            old_name='type',
            new_name='typeName',
        ),
    ]
