# Generated by Django 3.0.5 on 2020-05-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20200524_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_colours',
            field=models.ManyToManyField(to='cart.ColourVariation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(to='cart.SizeVariation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='threedimensionaldesign',
            name='available_colours',
            field=models.ManyToManyField(to='cart.ColourVariation'),
        ),
        migrations.AlterField(
            model_name='threedimensionaldesign',
            name='available_sizes',
            field=models.ManyToManyField(to='cart.SizeVariation'),
        ),
        migrations.AlterField(
            model_name='threedimensionaldesign',
            name='relatedType',
            field=models.ManyToManyField(to='cart.DesignVariation'),
        ),
    ]
