# Generated by Django 3.0.5 on 2020-05-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20200531_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
